In [ ]:
import pickle
from sklearn.linear_model import LinearRegression
import numpy as np

Below is a dummy ML model built from linear regression:

In [26]:
X = np.random.rand(3,3)
y = np.random.rand(3,2)

(array([[0.50446517, 0.76930233, 0.40165525],
        [0.19094312, 0.91446269, 0.59512754],
        [0.79488026, 0.89958788, 0.9797581 ]]),
 array([[0.8856119 , 0.36792745],
        [0.99879131, 0.93098345],
        [0.81167289, 0.00733913]]))

In [31]:
model = LinearRegression()
model.fit(X,y)
model.predict(np.array([1,2,3]).reshape(1,-1))[0]

array([0.86179794, 0.27796921])

In [28]:
picklefile = open('trained_model', 'wb')
#pickle the object and store it in a file
pickle.dump(model, picklefile)

In [29]:
#check that the object is correctly pickled and works when unpickled
del model
picklefile = open('trained_model', 'rb')
new_model = pickle.load(picklefile)
new_model.predict(np.array([1,2,3]).reshape(1,-1))

array([[0.86179794, 0.27796921]])